name: GJ-branch-CI

on: 
  push:
    branches: [ GJ-branch ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-lates
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 #Preuzimanje svih datoteka sa repo-a
        
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: GJ-branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
